### ISSUE TITLE
Package depends on PHPUnit?

### ISSUE THREAD

**Issue by sgotre** [Michael-Metz/PasswordProtect#2]
https://github.com/Michael-Metz/PasswordProtect/blob/1b13c4576ba5b4d4712792ed5a55dc876a9926b9/src/PasswordProtectController.php#L6

Are you sure this is the right HttpException Class?
have no PHPUnit in my live environment, thus the app can not boot.

**Comment by Michael-Metz** [comment]
I see your concern, you are saying that the HttpException class that PasswordProtectController.php is using belongs to PHPUnit.  Therefore if you don't have PHPUnit then the package will not work?  

**What happens if instead, you remove**
```php
 line 6  use Illuminate\Foundation\Testing\HttpException;  
```
**and examining the following uses on**

`line 83`
```php
throw new HttpException("recaptcha is config version:" .config('recaptcha.version') . "fix is needed to make this work with recaptcha again");
```

and `line 127`

```php
if ($validPassword == null)
            throw new HttpException("Password Protect: \"" . $rootRouteKey ."\" was not set in the .env file");
```

**we change to the following respectivly**

`line 83`

```php
abort(403, "recaptcha is config version:" .config('recaptcha.version') . "fix is needed to make this work with recaptcha again");
```

`line 127`

```php
if ($validPassword == null)
    abort(403,"Password Protect: \"" . $rootRouteKey ."\" was not set in the .env file");
```

Therefore we removed the dependency of `Illuminate\Foundation\Testing\HttpException` and all its uses within `PasswordProtectController.php` by replacing each time the exception was thrown, with just the `abort` helper function.
